config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]   
  get 'search', to: 'articles#search' 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories 
validates :title, presence: true, length: {minimum: 3, maximum: 20}
validates :user_id, presence:true
end

app/models/article_category.rb
class ArticleCategory<ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, uniqueness:true,length: {minimum:3, maximum:25}
end

app/models/user.rb
class User <ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save {self.email.downcase!}
    validates :username, presence:true,
              uniqueness:{case_sensitive:false},
              length:{minimum:3, maximum:25}
    VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence:true,
              uniqueness:{ case_sensitive:false },
              length:{ maximum:100},
              format:{ with: VALID_EMAIL_REGEX}
              has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :require_user
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:danger]="you must be logged in"
            redirect_to root_path
        end
        
    end
    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show,:index]
  before_action :require_same_user, only: [:edit,:update,:destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 2 )
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article Updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end

  end

  def create
    @article = Article.new(article_params)
    @article.user=current_user
    if @article.save
      flash[:success] = "Article Created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article destroyed"
    redirect_to articles_path
  end
  def search
    @result=params[:res]
    Article.all.each do |article|
      if   article.title==@result
        redirect_to article_path(article.id)
        return
      end
    end
        flash[:error]="Cant find article with name #{@result}"
        redirect_to root_path
end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])
  end
  def require_same_user
    if current_user!=@article.user && !current_user.admin?
      flash[:danger]="You can't edit or delete other's articles"
      redirect_to root_path
  end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index,:show]
    def new
        @category=Category.new
    end

    def index
        @categories=Category.paginate(page: params[:page],per_page:3)
    end
    def edit
        @category=Category.find(params[:id])
    end
    def update
        @category=Category.find(params[:id])
        if @category.update(set_params)
            flash[:success]="category updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end
    
    def show
        @category=Category.find(params[:id])
        @category_articles=@category.articles.paginate(page: params[:page],per_page:4)
    end
    def create
        @category=Category.new(set_params)
        if @category.save
            flash[:success]="category created"
            redirect_to categories_path
        else
            render 'new'
        end
    end
    private
    def set_params
        params.require(:category).permit(:name)
    end
    def require_admin
        if !logged_in?|| (logged_in? && !current_user.admin?)
            flash[:danger]="only admin can do that"
            redirect_to categories_path
        end

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create 
        user=User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id]=user.id
            flash[:success]="login successful"
            redirect_to user_path(user)
        else
            flash.now[:danger]="cant login"
            render 'new'
        end
    end
    def destroy
        session[:user_id]=nil
        flash[:success]="you have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
    before_action :set_user, only: [:edit,:update,:show,:destroy]
    before_action :require_same_user, only: [:edit, :update,:destroy]
    before_action :require_admin, only:[:destroy]
    def new
        @user=User.new
    end
    def create
        @user=User.new(set_params)
        if @user.save
            session[:user_id]=@user.id
            flash[:success]="Welcome to the alpha blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end
    def edit
    end
    def update
        if @user.update(set_params)
            flash[:success]="User updated"
            redirect_to articles_path
        else
            render 'new'
        end
    end
    def show
    end
    def index
        @users=User.paginate(page: params[:page],per_page:5)
    end
    def destroy
        @user.destroy
        flash[:danger]="User destroyed with his/her articles"
        redirect_to articles_path
    end
    private
    def set_params
        params.require(:user).permit(:username,:email,:password)
    end
    def set_user
        @user = User.find(params[:id])
      end
    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:danger]="You can't edit other users"
            redirect_to root_path
    end
  end
  def require_admin
    if logged_in? && !current_user.admin?
        flash[:danger]="You can't do that, you're not admin"
            redirect_to root_path
    end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/articles/_article.html.erb
<% obj.each do |art| %>
  <div class="row"></div>
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to art.title, article_path(art) %>
      </div>
      <div class="article-body">
        <%= truncate(art.description, length: 50) %>
      <div class="article-details">
        <p>Created by: <%= art.user.username if art.user%> ,
        <%= time_ago_in_words(art.updated_at)%> ago,
        last updated: <%= time_ago_in_words(art.updated_at)%> ago </p>
      </div>

      </div>
    <%if logged_in? && (current_user==art.user || current_user.admin?)%>
      <div class="row">
        <div class="col-ms-6">
          <%= link_to "Edit this article", edit_article_path(art), class: "btn btn-primary" %>
          <%= link_to "Delete this article", article_path(art), method: :delete, class: "btn btn-danger",
           data: {confirm: "are you sure ? "} %>
        </div>
      </div>
    <%end%>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors',obj:@article%>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "article title", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "article description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |chbx| %>
            <% chbx.label(class: "checkbox-inline input_checkbox") {chbx.check_box(class: "checkbox")+chbx.text}%>
            <%end%>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div style="text-decoration: underline; font-weight: bold"
        class="col-sm-offset-5">
      <%= link_to "Cancel and Back to articles", articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">All articles</h1>
<div align="center">
<%=will_paginate%>
</div>
  <%= render 'article',obj:@articles%>
  <div align="center">
<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%=	render 'form'  %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
<% if @article.user%>
<ul class="listing">
  <div class="row">
  <h3 align="center">Author : </h3>
    <div align="center" class="col-md-4 col-md-offset-4">
        <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user)%>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
    </div>
  </div>
</ul>
<%end%>
  <h3 align="center">Description: </h3>
  <hr>
  <%= simple_format(@article.description) %>
  <%if @article.categories.any?%>
  <p>Categories: <%= render @article.categories %></p>
  <%end%>
  <%if logged_in? && (current_user==@article.user || current_user.admin?)%>
  <div class="row">
    <div class="col-ms-6">
      <%= link_to "Edit this article", edit_article_path(@article), class:"btn btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, class: "btn btn-danger", data: {confirm: "are you sure ? "} %>
    </div>
  </div>
  <%end%>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%=link_to category.name, category_path(category) %> </span>

app/views/categories/_form.html.erb
  <%= render 'shared/errors',obj:@category%>
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
    <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "category name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div style="text-decoration: underline; font-weight: bold"
          class="col-sm-offset-5">
      <%= link_to "Cancel and Back to articles", articles_path %>
    </div>
  </div>
  </div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">All categories</h1>
<h4 align="center"><%=will_paginate%></p>
<% @categories.each do |category|%>
    <ul class="listing">
        <div class="row">
            <div class="well col-md-4 col-md-offset-4">
                <li class="article-title">
                <%= link_to "#{category.name}", category_path(category) %>
                </li>
                <small><%= "#{category.articles.count} Article(s) in here"%></small>
            </div>
        </div>
    </ul>
<%end%>  
<h4 align="center"><%=will_paginate%></p>

app/views/categories/new.html.erb
  <h1 align="center">Create new category</h1>
  <%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%="Category #{@category.name}"%></h1>
<div align="center">

<% if logged_in? && current_user.admin? %>
    <div class="row">
        <span class="badge"><%= link_to 'Edit', edit_category_path(@category) %></span>
    </div>
<% end %>
    <%=will_paginate @category_articles%>
</div>
    <%= render 'articles/article',obj:@category_articles%>
    <div align="center">
<%= will_paginate @category_articles %>
</div>

app/views/layouts/_flashload.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    @Copyright 2018.
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Articles", articles_path   %></li>
      <li><%= link_to "Users", users_path   %></li>
       <% if logged_in? %>  
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
<% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Categories", categories_path  %></li>
            <%Category.all.each do |cat|%>
            <li><%= link_to "#{cat.name}",category_path(cat)%></li>
            <%end%>
            <%if logged_in? && current_user.admin?%>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Add new', new_category_path %></li>
            <%end%>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" action=<%=search_path%>>
        <div class="form-group">
          <input type="text" name="res" class="form-control" placeholder="Search" >
        </div>
        <button type="submit" class="btn btn-default" >Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%if logged_in? %>
        <li><%= link_to 'Log out',logout_path, method: :delete%> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
          aria-expanded="false">Your Profile <%= "Admin" if current_user.admin?%>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to 'Edit profile',edit_user_path(current_user)%></li>
            <li><%=link_to 'View profile',user_path(current_user)%></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
          </li>
        <%else%>
          <li><%= link_to 'Log in',login_path%> </li>
          <li><%= link_to 'Sign up',signup_path%> </li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/flashload' %>
<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron" style="text-align: center">
<h1>Alpha Blog</h1>
<%= link_to "Sign up now", signup_path ,class: "btn btn-primary btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prevented article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li>  <%= msg %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors',obj:@user%>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "email" %>
        </div>
      </div>
         <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account",
           class: "btn btn-primary btn-lg") %>
        </div>
      </div>
    <% end %>
    <div style="text-decoration: underline; font-weight: bold"
         class="col-sm-offset-5">
      <%= link_to "Cancel and Back to articles", articles_path %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit account </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div align="center">
<%= will_paginate%>
    <% @users.each do |user| %> 
<ul class="listing">
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
        <li class="article-title">
            <%= link_to user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        <%if logged_in? && current_user.admin?%>
        <li class="btn btn-danger"><%=link_to "Delete User",user_path(user),method: :delete,
        data: {confirm: "Are you sure you want to delete user and it's all articles? "}%></li>
        <%end%>
    </div>
  </div>
</ul>
<% end %>

app/views/users/new.html.erb
<h1 align="center">Sign Up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%=@user.username%>'s page </h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    </div>
</div>
<h4 align="center">articles of <%= @user.username %>:</h4>
<%= render 'articles/article',obj:@user.articles %>